#!/usr/bin/env bash
# Entry point script for code agents in Docker sandbox.
#
# This script is copied into the sandbox and executed to start a code agent.
# It supports three agents, selected via the CLOMA_AGENT environment variable:
#
#   - claude (default): Claude Code, driven by the Anthropic Messages API.
#   - grok:             Grok Build, driven by an OpenAI-compatible endpoint.
#   - kimi:             Kimi Code, driven by an OpenAI-compatible endpoint.
#
# All agents are pointed at an Ollama instance running on the host. Ollama is
# verified with its native API, then the selected agent is launched with a
# model from CLOMA_MODEL and optional extra flags from CLOMA_FLAGS.

set -euo pipefail

# Configuration with defaults (can be overridden via environment)
CLOMA_AGENT="${CLOMA_AGENT:-claude}"
CLOMA_MODEL="${CLOMA_MODEL:-glm-5:cloud}"
CLOMA_OLLAMA_URL="${CLOMA_OLLAMA_URL:-http://host.docker.internal:11434}"
CLOMA_FLAGS="${CLOMA_FLAGS:-}"
WORKSPACE="${WORKSPACE:-$PWD}"

# Make sure the per-user agent install locations are on PATH
# (grok installs to ~/.grok/bin, kimi installs to ~/.kimi-code/bin).
export PATH="${HOME}/.kimi-code/bin:${HOME}/.grok/bin:${HOME}/.local/bin:${PATH}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

log_info() {
  printf '%b[INFO]%b %s\n' "${GREEN}" "${NC}" "$1"
}

log_warn() {
  printf '%b[WARN]%b %s\n' "${YELLOW}" "${NC}" "$1" >&2
}

log_error() {
  printf '%b[ERROR]%b %s\n' "${RED}" "${NC}" "$1" >&2
}

# Verify Ollama connectivity using its native API (works for both agents).
verify_ollama() {
  log_info "Verifying Ollama connectivity at ${CLOMA_OLLAMA_URL}..."

  local max_attempts=10
  local attempt

  for attempt in $(seq 1 "${max_attempts}"); do
    if curl -fsS "${CLOMA_OLLAMA_URL}/api/tags" >/dev/null 2>&1; then
      log_info "Ollama is reachable"
      return 0
    fi
    log_warn "Attempt ${attempt}/${max_attempts}: Cannot reach Ollama"
    sleep 1
  done

  log_error "Cannot reach Ollama at ${CLOMA_OLLAMA_URL}"
  log_error "Ensure Ollama is running on the host: ollama serve"
  exit 1
}

# Verify model exists in Ollama.
verify_model() {
  log_info "Checking for model: ${CLOMA_MODEL}"

  if curl -fsS -o /dev/null "${CLOMA_OLLAMA_URL}/api/show" -d "{\"model\":\"${CLOMA_MODEL}\"}" 2>/dev/null; then
    log_info "Model ${CLOMA_MODEL} is available"
    return 0
  fi

  log_error "Model ${CLOMA_MODEL} not found in Ollama"
  log_error "Pull it first: ollama pull ${CLOMA_MODEL}"
  exit 1
}

# Print startup information
print_info() {
  local agent_name
  case "${CLOMA_AGENT}" in
    grok)   agent_name="Grok Build" ;;
    kimi)   agent_name="Kimi Code" ;;
    claude) agent_name="Claude Code" ;;
    *)      agent_name="${CLOMA_AGENT}" ;;
  esac

  printf '\n'
  printf '===========================================\n'
  printf '     %s - Docker Sandbox\n' "${agent_name}"
  printf '===========================================\n'
  printf '\n'
  printf 'Configuration:\n'
  printf '  Agent:     %s\n' "${agent_name}"
  printf '  Model:     %s\n' "${CLOMA_MODEL}"
  printf '  Ollama:    %s\n' "${CLOMA_OLLAMA_URL}"
  printf '  Workspace: %s\n' "${WORKSPACE}"
  if [ -n "${CLOMA_FLAGS}" ]; then
    printf '  Flags:     %s\n' "${CLOMA_FLAGS}"
  fi
  printf '\n'
}

# Install the selected agent CLI if it is not already available.
ensure_agent_installed() {
  case "${CLOMA_AGENT}" in
    claude)
      if command -v claude >/dev/null 2>&1; then
        return 0
      fi
      log_info "Installing Claude Code..."
      curl -fsSL https://claude.ai/install.sh | bash
      ;;
    grok)
      if command -v grok >/dev/null 2>&1; then
        return 0
      fi
      log_info "Installing Grok Build..."
      curl -fsSL https://x.ai/cli/install.sh | bash
      ;;
    kimi)
      if command -v kimi >/dev/null 2>&1; then
        return 0
      fi
      log_info "Installing Kimi Code..."
      curl -fsSL https://code.kimi.com/kimi-code/install.sh | bash
      ;;
    *)
      log_error "Unknown agent: ${CLOMA_AGENT} (expected 'claude', 'grok' or 'kimi')"
      exit 1
      ;;
  esac
}

# Write Grok Build's config so it targets the host Ollama via the
# OpenAI-compatible /v1 endpoint. No login is required because the model
# entry carries its own (dummy) API key.
write_grok_config() {
  local config_dir="${HOME}/.grok"
  local config_file="${config_dir}/config.toml"

  mkdir -p "${config_dir}"

  # Use a stable custom-model key so the same value works with `grok -m ollama`.
  cat > "${config_file}" <<EOF
# Generated by cloma. Points Grok Build at the host Ollama instance.
[model.ollama]
model = "${CLOMA_MODEL}"
base_url = "${CLOMA_OLLAMA_URL}/v1"
name = "Ollama (${CLOMA_MODEL})"
api_backend = "chat_completions"
api_key = "ollama"
EOF

  log_info "Wrote grok config to ${config_file}"
}

# Launch Claude Code.
launch_claude() {
  # Claude Code speaks the Anthropic Messages API; Ollama exposes a
  # compatible endpoint at the configured base URL.
  export ANTHROPIC_AUTH_TOKEN="${ANTHROPIC_AUTH_TOKEN:-ollama}"
  export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
  export ANTHROPIC_BASE_URL="${CLOMA_OLLAMA_URL}"

  log_info "Launching Claude Code with model: ${CLOMA_MODEL}"
  printf '\n'

  if [ -n "${CLOMA_FLAGS}" ]; then
    exec claude --model "${CLOMA_MODEL}" ${CLOMA_FLAGS}
  else
    exec claude --model "${CLOMA_MODEL}"
  fi
}

# Launch Grok Build.
launch_grok() {
  # Grok reads its model catalog from ~/.grok/config.toml (written above).
  # A dummy API key satisfies Grok's credential check so it does not prompt
  # for browser login when pointed at a local Ollama instance.
  export XAI_API_KEY="${XAI_API_KEY:-ollama}"

  log_info "Launching Grok Build with model: ollama (${CLOMA_MODEL})"
  printf '\n'

  # The `-m ollama` selects the custom model entry written by write_grok_config.
  if [ -n "${CLOMA_FLAGS}" ]; then
    exec grok -m ollama ${CLOMA_FLAGS}
  else
    exec grok -m ollama
  fi
}

# Kimi Code's OpenAI client is Node fetch (undici), which cannot reach the
# host Ollama through cloma's network proxy: the proxy accepts only
# non-tunneling requests (curl-style), while undici ignores HTTP_PROXY by
# default and tunnels (CONNECT) when forced via NODE_USE_ENV_PROXY, which the
# proxy rejects. The sandbox's localhost:<port> is not directly mapped to the
# host either. So we run a tiny local relay that kimi's fetch talks to
# directly (127.0.0.1), and which forwards to Ollama through the proxy the
# way curl does (non-tunneling).
KIMI_RELAY_PORT="${KIMI_RELAY_PORT:-18999}"

# Start the local Ollama relay (idempotent — reuses one already listening).
start_kimi_relay() {
  if ! command -v python3 >/dev/null 2>&1; then
    log_error "python3 is required for the kimi Ollama relay but was not found"
    log_error "re-provision the sandbox: cloma run --agent kimi"
    exit 1
  fi

  # Reuse a relay that is already listening (e.g. from a previous launch).
  if curl -s --noproxy '*' --max-time 1 \
      "http://127.0.0.1:${KIMI_RELAY_PORT}/api/version" >/dev/null 2>&1; then
    log_info "kimi Ollama relay already running on 127.0.0.1:${KIMI_RELAY_PORT}"
    return 0
  fi

  local relay="${HOME}/.kimi-code/ollama_relay.py"
  cat > "${relay}" <<'PYEOF'
#!/usr/bin/env python3
"""Local non-tunneling relay: fetch -> 127.0.0.1:PORT -> (HTTP_PROXY) -> Ollama.
Node fetch cannot use cloma's non-tunneling-only proxy; this relay forwards
like curl does, so kimi only ever talks to localhost."""
import http.server, urllib.request, sys, os
UPSTREAM = os.environ.get("KIMI_RELAY_UPSTREAM", "http://host.docker.internal:11434")
PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 18999

class H(http.server.BaseHTTPRequestHandler):
    def log_message(self, *a): pass
    def _forward(self):
        n = int(self.headers.get("Content-Length", 0) or 0)
        body = self.rfile.read(n) if n else None
        req = urllib.request.Request(UPSTREAM + self.path, data=body, method=self.command)
        for k, v in self.headers.items():
            if k.lower() in ("host", "content-length", "accept-encoding",
                             "proxy-connection", "connection"):
                continue
            req.add_header(k, v)
        try:
            resp = urllib.request.urlopen(req, timeout=600)
        except urllib.error.HTTPError as e:
            resp = e
        self.send_response(resp.status)
        for k, v in resp.headers.items():
            if k.lower() in ("transfer-encoding", "connection", "content-length"):
                continue
            self.send_header(k, v)
        self.end_headers()
        while True:
            chunk = resp.read(4096)
            if not chunk:
                break
            self.wfile.write(chunk); self.wfile.flush()
    do_GET = _forward
    do_POST = _forward

http.server.ThreadingHTTPServer(("127.0.0.1", PORT), H).serve_forever()
PYEOF

  # Detached so it survives `exec kimi`; dies when the sandbox stops.
  KIMI_RELAY_UPSTREAM="${CLOMA_OLLAMA_URL}" setsid python3 "${relay}" "${KIMI_RELAY_PORT}" \
    >/tmp/kimi-relay.log 2>&1 </dev/null &

  local i
  for i in $(seq 1 25); do
    if curl -s --noproxy '*' --max-time 1 \
        "http://127.0.0.1:${KIMI_RELAY_PORT}/api/version" >/dev/null 2>&1; then
      log_info "kimi Ollama relay listening on 127.0.0.1:${KIMI_RELAY_PORT} -> ${CLOMA_OLLAMA_URL}"
      return 0
    fi
    sleep 0.2
  done
  log_error "kimi Ollama relay failed to start (see /tmp/kimi-relay.log)"
  exit 1
}

# Write Kimi Code's config so it targets the local relay (which forwards to
# the host Ollama via the OpenAI-compatible /v1 endpoint). A dummy API key
# satisfies Kimi Code's credential requirement so it does not prompt for
# OAuth login when pointed at a local Ollama instance.
write_kimi_config() {
  local config_dir="${HOME}/.kimi-code"
  local config_file="${config_dir}/config.toml"

  mkdir -p "${config_dir}"

  local kimi_base_url="http://127.0.0.1:${KIMI_RELAY_PORT}/v1"

  # The "ollama" model alias selects the custom provider entry below.
  # `default_model` makes `kimi` (with no -m) use Ollama automatically.
  cat > "${config_file}" <<EOF
# Generated by cloma. Points Kimi Code at the local relay -> host Ollama.
default_model = "ollama"
default_permission_mode = "manual"

[providers.ollama]
type = "openai"
base_url = "${kimi_base_url}"
api_key = "ollama"

[models.ollama]
provider = "ollama"
model = "${CLOMA_MODEL}"
max_context_size = 262144
EOF

  log_info "Wrote kimi config to ${config_file} (base_url=${kimi_base_url})"
}

# Launch Kimi Code.
launch_kimi() {
  # Kimi reads its providers and models from ~/.kimi-code/config.toml
  # (written above). A dummy API key is embedded in the provider entry so
  # Kimi Code runs against the local Ollama without OAuth login.
  # Disable the update preflight and telemetry so the sandboxed agent does
  # not attempt outbound network calls it cannot reach.
  export KIMI_CODE_NO_AUTO_UPDATE="${KIMI_CODE_NO_AUTO_UPDATE:-1}"
  export KIMI_DISABLE_TELEMETRY="${KIMI_DISABLE_TELEMETRY:-1}"

  # Start the local relay that bridges kimi's fetch to the host Ollama.
  start_kimi_relay

  log_info "Launching Kimi Code with model: ollama (${CLOMA_MODEL})"
  printf '\n'

  # `-m ollama` selects the custom model entry written by write_kimi_config.
  if [ -n "${CLOMA_FLAGS}" ]; then
    exec kimi -m ollama ${CLOMA_FLAGS}
  else
    exec kimi -m ollama
  fi
}

# Main entry point
main() {
  print_info

  # Verify connectivity
  verify_ollama
  verify_model

  # Change to workspace directory
  if [ -d "${WORKSPACE}" ]; then
    cd "${WORKSPACE}"
    log_info "Working directory: ${WORKSPACE}"
  else
    log_warn "Workspace does not exist: ${WORKSPACE}, using current directory"
  fi

  # Make sure the selected agent CLI is present
  ensure_agent_installed

  # Launch the selected agent
  case "${CLOMA_AGENT}" in
    claude)
      launch_claude
      ;;
    grok)
      write_grok_config
      launch_grok
      ;;
    kimi)
      write_kimi_config
      launch_kimi
      ;;
    *)
      log_error "Unknown agent: ${CLOMA_AGENT} (expected 'claude', 'grok' or 'kimi')"
      exit 1
      ;;
  esac
}

# Run main
main "$@"